import { Locale } from './translations';

export interface Project {
  slug: string;
  title: string;
  description: string;
  longDescription: string;
  technologies: string[];
  category: string;
  projectType: string;
  semester: string;
  image: string;
  images?: string[];
  features: string[];
  challenges?: string[];
  results?: string[];
  github?: string;
  codeExamples?: { title: string; code: string }[];
}

// Fonction pour obtenir les projets traduits
export const getProjectsData = (locale: Locale): Project[] => {
  return projectsTranslations[locale];
};

// Fonction pour obtenir un projet par son slug
export const getProjectBySlug = (slug: string, locale: Locale): Project | undefined => {
  return projectsTranslations[locale].find(p => p.slug === slug);
};

const projectsTranslations: Record<Locale, Project[]> = {
  fr: [
    {
      slug: "biosymphonie",
      title: "BioSymphonie - Site Web Écoresponsable",
      description: "Création d'un site web complet pour une entreprise d'événements écoresponsables avec navigation multilingue, carousel d'images et design responsive.",
      longDescription: `Ce projet consistait à créer un site web complet pour BioSymphonie, une entreprise fictive spécialisée dans l'organisation d'événements écoresponsables. 

Le site devait répondre aux besoins spécifiques du client avec une approche moderne et respectueuse de l'environnement. J'ai travaillé sur tous les aspects du développement, de la conception à la mise en ligne.`,
      technologies: ["HTML5", "CSS3", "JavaScript", "Responsive Design"],
      category: "Web Development",
      projectType: "Projets étudiants",
      semester: "S1 - 2024",
      image: "/biosymphonie.png",
      images: ["/biosymphonie.png"],
      features: [
        "Navigation multilingue (Français/Anglais)",
        "Design responsive adaptatif",
        "Carousel d'images interactif",
        "Formulaire de contact fonctionnel",
        "Conformité RGPD avec banner cookies",
        "Optimisation SEO",
        "Animations CSS fluides",
        "Structure HTML5 sémantique",
      ],
      challenges: [
        "Implémentation de la navigation multilingue",
        "Optimisation des performances sur mobile",
        "Respect des normes d'accessibilité WCAG",
        "Intégration des contraintes RGPD",
      ],
      results: [
        "Site 100% responsive sur tous appareils",
        "Temps de chargement optimisé < 2s",
        "Navigation fluide et intuitive",
        "Conformité légale complète",
      ],
    },
    {
      slug: "echecs",
      title: "Jeu d'Échecs Interactif",
      description: "Application web de jeu d'échecs en ligne avec interface graphique complète, gestion des tours et système de promotion des pions.",
      longDescription: `Développement d'une application complète de jeu d'échecs avec interface web interactive. Le projet incluait la programmation de toute la logique de jeu, la gestion des règles d'échecs et une interface utilisateur intuitive.`,
      technologies: ["Java", "JavaFX", "Interface Web", "Logique de jeu"],
      category: "Game Development",
      projectType: "Projets étudiants",
      semester: "S1 - 2024",
      image: "/echecs.png",
      images: ["/echecs.png"],
      features: [
        "Interface graphique complète",
        "Gestion des tours de jeu",
        "Système de promotion des pions",
        "Validation des mouvements",
        "Messages d'erreur appropriés",
        "Gestion du temps de jeu",
        "Interface web responsive",
      ],
      challenges: [
        "Implémentation des règles complexes d'échecs",
        "Gestion des cas spéciaux (roque, en passant)",
        "Optimisation de l'interface utilisateur",
        "Validation en temps réel des mouvements",
      ],
      results: [
        "Jeu d'échecs entièrement fonctionnel",
        "Interface intuitive et responsive",
        "Respect complet des règles officielles",
        "Performance optimisée",
      ],
    },
    {
      slug: "bomberman",
      title: "Bomberman - Jeu 2D JavaFX",
      description: "Développement d'un jeu Bomberman complet avec architecture MVC, animations fluides et gestion des explosions.",
      longDescription: `Création d'un jeu Bomberman en JavaFX avec une architecture MVC robuste. Le projet incluait la gestion des personnages, des explosions, des animations et une interface utilisateur complète.`,
      technologies: ["JavaFX", "MVC Pattern", "Animation", "Observer Pattern"],
      category: "Game Development",
      projectType: "Projets étudiants",
      semester: "S2 - 2025",
      image: "/bomberman.png",
      images: ["/bomberman.png"],
      features: [
        "Architecture MVC complète",
        "Animations Timeline fluides",
        "Gestion des explosions",
        "Interface responsive",
        "Observer Pattern pour la réactivité",
        "Binding JavaFX avancé",
        "Thread-safety avec Platform.runLater",
      ],
      github: "https://github.com/XiVolt/Bomberman",
    },
    {
      slug: "procyon",
      title: "Infrastructure Réseau Procyon",
      description: "Configuration complète d'une infrastructure réseau avec services DNS/Web, sécurisation et haute disponibilité.",
      longDescription: `Configuration d'une infrastructure réseau complète incluant des services DNS et Web, avec une attention particulière à la sécurisation et à la haute disponibilité.`,
      technologies: ["Linux", "DNS (BIND)", "Apache", "IPv4/IPv6", "Sécurité"],
      category: "System Administration",
      projectType: "Projets étudiants",
      semester: "S2 - 2025",
      image: "/setup.png",
      images: ["/setup.png"],
      features: [
        "Configuration DNS maître/esclave",
        "Virtual hosts Apache",
        "Sécurisation par zones",
        "Haute disponibilité",
      ],
    },
    {
      slug: "algorithmes-tri",
      title: "Analyse d'Algorithmes de Tri",
      description: "Projet d'analyse comparative de performance entre différents algorithmes de tri avec mesures de complexité temporelle et optimisations.",
      longDescription: `Analyse approfondie des algorithmes de tri classiques avec comparaison de leurs performances sur différentes tailles de données.`,
      technologies: ["Java", "Algorithmique", "Analyse de Performance", "Tests Unitaires"],
      category: "Algorithm Analysis",
      projectType: "Projets étudiants",
      semester: "S1 - 2024",
      image: "/tri.png",
      images: ["/tri.png"],
      features: [
        "Implémentation Tri Fusion O(n log n)",
        "Tri Rapide avec pivot optimisé",
        "Mesures de performance temps réel",
        "Analyse comparative sur grandes données",
      ],
    },
    {
      slug: "base-de-donnees",
      title: "Base de Données Démographique",
      description: "Conception et exploitation d'une base de données relationnelle complexe avec modélisation hiérarchique et requêtes optimisées.",
      longDescription: `Conception d'une base de données relationnelle pour la gestion de données démographiques avec optimisation des requêtes.`,
      technologies: ["SQL", "PostgreSQL", "Modélisation", "Optimisation"],
      category: "Database",
      projectType: "Projets étudiants",
      semester: "S2 - 2025",
      image: "/bd.png",
      images: ["/bd.png"],
      features: [
        "Modélisation hiérarchique",
        "Jointures optimisées",
        "Requêtes sécurisées",
        "Protection des données",
      ],
    },
    {
      slug: "portfolio-nextjs",
      title: "Portfolio Personnel - Next.js",
      description: "Développement de ce portfolio avec Next.js, animations Framer Motion, mode sombre/clair et optimisations performance.",
      longDescription: `Ce portfolio a été développé avec Next.js et présente mes projets et compétences de manière interactive.`,
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
      category: "Web Development",
      projectType: "Projets personnels",
      semester: "Projet Personnel",
      image: "/portfolio.png",
      images: ["/portfolio.png"],
      features: [
        "Mode sombre/clair",
        "Animations fluides",
        "Performance optimisée",
        "SEO avancé",
      ],
      github: "https://github.com/XiVolt/Portfolio",
    },
    {
      slug: "volturacode-website",
      title: "VolturaCode - Site d'entreprise",
      description: "Développement du site vitrine de mon entreprise VolturaCode, spécialisée dans le développement web et la cybersécurité.",
      longDescription: `Site vitrine professionnel pour mon entreprise VolturaCode, présentant les services et réalisations.`,
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "React"],
      category: "Web Development",
      projectType: "Projets personnels",
      semester: "Projet Personnel",
      image: "/Voltura.png",
      images: ["/Voltura.png"],
      features: [
        "Design moderne",
        "Site vitrine responsive",
        "Présentation des services",
        "Portfolio client",
      ],
      github: "https://github.com/XiVolt/voltura-code-site",
    },
    {
      slug: "jeu-c",
      title: "Jeu en C - Développement bas niveau",
      description: "Développement d'un jeu en langage C avec gestion de la mémoire, programmation bas niveau et interface console.",
      longDescription: `Développement d'un jeu en langage C avec une attention particulière à la gestion de la mémoire et la programmation bas niveau.`,
      technologies: ["C", "Gestion mémoire", "Algorithmique"],
      category: "Game Development",
      projectType: "Projets personnels",
      semester: "Projet Personnel",
      image: "/placeholder.png",
      images: ["/placeholder.png"],
      features: [
        "Programmation bas niveau",
        "Gestion de la mémoire",
        "Interface console",
        "Logique de jeu",
      ],
      github: "https://github.com/XiVolt/Fracture-UP",
    },
    {
      slug: "onlyfoot",
      title: "OnlyFoot - Réseau social football",
      description: "Site web communautaire sur le football : partage de photos, profils utilisateurs, commentaires, likes et base de données PostgreSQL.",
      longDescription: `Plateforme sociale dédiée au football permettant aux utilisateurs de partager leurs moments sportifs.`,
      technologies: ["React", "Node.js", "Express", "PostgreSQL", "SQL", "Cloudinary"],
      category: "Web Development",
      projectType: "Projets personnels",
      semester: "Projet Personnel",
      image: "/onlyfoot.png",
      images: ["/onlyfoot.png"],
      features: [
        "Création de profils utilisateurs",
        "Publication de photos de football",
        "Commentaires et likes sur les posts",
        "Base de données relationnelle PostgreSQL",
        "API Node.js sécurisée",
        "Gestion des images avec Cloudinary",
      ],
    },
    {
      slug: "lensymphony-java",
      title: "LenSymphony - Synthétiseur Musical Java",
      description: "Développement d'un synthétiseur musical fonctionnel en Java avec lecture de partitions XML et génération de sons en temps réel.",
      longDescription: `Synthétiseur musical complet développé en Java permettant la lecture de partitions au format XML.`,
      technologies: ["Java", "XML", "Algorithmique musicale"],
      category: "Software Development",
      projectType: "Projets étudiants",
      semester: "S3 - 2025",
      image: "/Lensymphony2.png",
      images: ["/Lensymphony2.png"],
      features: [
        "Synthétiseur musical complet",
        "Lecture de partitions XML",
        "Génération de sons en temps réel",
        "Interface utilisateur Java",
      ],
      github: "https://gitlab.univ-artois.fr/leo_regniez1/lensymphony-groupe-b-4-regniez-leo-bras-tristan-plouvin-nathan-strobbe-theo",
    },
    {
      slug: "lensymphony-php",
      title: "LenSymphony - Site Web PHP",
      description: "Développement d'un site web en PHP pour présenter et jouer les musiques créées avec le synthétiseur LenSymphony.",
      longDescription: `Site web de présentation pour le projet LenSymphony, permettant d'écouter les musiques générées.`,
      technologies: ["PHP", "Sqlite", "CSS3", "JavaScript"],
      category: "Web Development",
      projectType: "Projets étudiants",
      semester: "S3 - 2025",
      image: "/Lensymphony.png",
      images: ["/Lensymphony.png"],
      features: [
        "Galerie de musiques",
        "Lecteur audio intégré",
        "Interface de présentation",
        "Base de données SQLite",
      ],
      github: "https://gitlab.univ-artois.fr/nathan_plouvin/leo-tristan-theo-nathan-lensymphony-web",
    },
    {
      slug: "marathon-web-blues",
      title: "Marathon du Web - Blog Musical Blues",
      description: "Développement d'un site blog dédié au blues lors d'un marathon du web, avec articles, playlists et découverte d'artistes.",
      longDescription: `Blog thématique sur le blues créé lors d'un marathon du web, présentant l'histoire et les artistes du genre.`,
      technologies: ["PHP", "Sqlite", "CSS3", "JavaScript", "Responsive Design"],
      category: "Web Development",
      projectType: "Projets étudiants",
      semester: "S3 - 2025",
      image: "/Marathon.png",
      images: ["/Marathon.png"],
      features: [
        "Blog musical thématique",
        "Articles sur le blues",
        "Playlists et découvertes",
        "Design responsive",
      ],
      github: "https://gitlab.univ-artois.fr/nathan_plouvin/code-marathon-2025-groupe-10",
    },
  ],
  en: [
    {
      slug: "biosymphonie",
      title: "BioSymphonie - Eco-Responsible Website",
      description: "Creation of a complete website for an eco-responsible events company with multilingual navigation, image carousel and responsive design.",
      longDescription: `This project consisted of creating a complete website for BioSymphonie, a fictional company specializing in organizing eco-responsible events. 

The site had to meet the specific needs of the client with a modern and environmentally friendly approach. I worked on all aspects of development, from design to deployment.`,
      technologies: ["HTML5", "CSS3", "JavaScript", "Responsive Design"],
      category: "Web Development",
      projectType: "Student projects",
      semester: "S1 - 2024",
      image: "/biosymphonie.png",
      images: ["/biosymphonie.png"],
      features: [
        "Multilingual navigation (French/English)",
        "Adaptive responsive design",
        "Interactive image carousel",
        "Functional contact form",
        "GDPR compliant cookie banner",
        "SEO optimization",
        "Smooth CSS animations",
        "Semantic HTML5 structure",
      ],
      challenges: [
        "Implementing multilingual navigation",
        "Mobile performance optimization",
        "WCAG accessibility standards compliance",
        "GDPR constraints integration",
      ],
      results: [
        "100% responsive on all devices",
        "Optimized loading time < 2s",
        "Smooth and intuitive navigation",
        "Complete legal compliance",
      ],
    },
    {
      slug: "echecs",
      title: "Interactive Chess Game",
      description: "Online chess game web application with complete graphical interface, turn management and pawn promotion system.",
      longDescription: `Development of a complete chess game application with interactive web interface. The project included programming all game logic, managing chess rules and an intuitive user interface.`,
      technologies: ["Java", "JavaFX", "Web Interface", "Game Logic"],
      category: "Game Development",
      projectType: "Student projects",
      semester: "S1 - 2024",
      image: "/echecs.png",
      images: ["/echecs.png"],
      features: [
        "Complete graphical interface",
        "Turn management",
        "Pawn promotion system",
        "Movement validation",
        "Appropriate error messages",
        "Game time management",
        "Responsive web interface",
      ],
      challenges: [
        "Implementing complex chess rules",
        "Handling special cases (castling, en passant)",
        "User interface optimization",
        "Real-time movement validation",
      ],
      results: [
        "Fully functional chess game",
        "Intuitive and responsive interface",
        "Complete compliance with official rules",
        "Optimized performance",
      ],
    },
    {
      slug: "bomberman",
      title: "Bomberman - 2D JavaFX Game",
      description: "Development of a complete Bomberman game with MVC architecture, smooth animations and explosion management.",
      longDescription: `Creation of a Bomberman game in JavaFX with a robust MVC architecture. The project included character management, explosions, animations and a complete user interface.`,
      technologies: ["JavaFX", "MVC Pattern", "Animation", "Observer Pattern"],
      category: "Game Development",
      projectType: "Student projects",
      semester: "S2 - 2025",
      image: "/bomberman.png",
      images: ["/bomberman.png"],
      features: [
        "Complete MVC architecture",
        "Smooth Timeline animations",
        "Explosion management",
        "Responsive interface",
        "Observer Pattern for reactivity",
        "Advanced JavaFX binding",
        "Thread-safety with Platform.runLater",
      ],
      github: "https://github.com/XiVolt/Bomberman",
    },
    {
      slug: "procyon",
      title: "Procyon Network Infrastructure",
      description: "Complete configuration of a network infrastructure with DNS/Web services, security and high availability.",
      longDescription: `Configuration of a complete network infrastructure including DNS and Web services, with particular attention to security and high availability.`,
      technologies: ["Linux", "DNS (BIND)", "Apache", "IPv4/IPv6", "Security"],
      category: "System Administration",
      projectType: "Student projects",
      semester: "S2 - 2025",
      image: "/setup.png",
      images: ["/setup.png"],
      features: [
        "Master/slave DNS configuration",
        "Apache virtual hosts",
        "Zone-based security",
        "High availability",
      ],
    },
    {
      slug: "algorithmes-tri",
      title: "Sorting Algorithms Analysis",
      description: "Comparative performance analysis project between different sorting algorithms with time complexity measurements and optimizations.",
      longDescription: `In-depth analysis of classic sorting algorithms with performance comparison on different data sizes.`,
      technologies: ["Java", "Algorithmics", "Performance Analysis", "Unit Tests"],
      category: "Algorithm Analysis",
      projectType: "Student projects",
      semester: "S1 - 2024",
      image: "/tri.png",
      images: ["/tri.png"],
      features: [
        "Merge Sort implementation O(n log n)",
        "Quick Sort with optimized pivot",
        "Real-time performance measurements",
        "Comparative analysis on large data",
      ],
    },
    {
      slug: "base-de-donnees",
      title: "Demographic Database",
      description: "Design and operation of a complex relational database with hierarchical modeling and optimized queries.",
      longDescription: `Design of a relational database for demographic data management with query optimization.`,
      technologies: ["SQL", "PostgreSQL", "Modeling", "Optimization"],
      category: "Database",
      projectType: "Student projects",
      semester: "S2 - 2025",
      image: "/bd.png",
      images: ["/bd.png"],
      features: [
        "Hierarchical modeling",
        "Optimized joins",
        "Secure queries",
        "Data protection",
      ],
    },
    {
      slug: "portfolio-nextjs",
      title: "Personal Portfolio - Next.js",
      description: "Development of this portfolio with Next.js, Framer Motion animations, dark/light mode and performance optimizations.",
      longDescription: `This portfolio was developed with Next.js and presents my projects and skills interactively.`,
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
      category: "Web Development",
      projectType: "Personal projects",
      semester: "Personal Project",
      image: "/portfolio.png",
      images: ["/portfolio.png"],
      features: [
        "Dark/light mode",
        "Smooth animations",
        "Optimized performance",
        "Advanced SEO",
      ],
      github: "https://github.com/XiVolt/Portfolio",
    },
    {
      slug: "volturacode-website",
      title: "VolturaCode - Company Website",
      description: "Development of the showcase website for my company VolturaCode, specializing in web development and cybersecurity.",
      longDescription: `Professional showcase website for my company VolturaCode, presenting services and achievements.`,
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "React"],
      category: "Web Development",
      projectType: "Personal projects",
      semester: "Personal Project",
      image: "/Voltura.png",
      images: ["/Voltura.png"],
      features: [
        "Modern design",
        "Responsive showcase site",
        "Services presentation",
        "Client portfolio",
      ],
      github: "https://github.com/XiVolt/voltura-code-site",
    },
    {
      slug: "jeu-c",
      title: "C Game - Low Level Development",
      description: "Development of a game in C language with memory management, low-level programming and console interface.",
      longDescription: `Development of a game in C language with particular attention to memory management and low-level programming.`,
      technologies: ["C", "Memory Management", "Algorithmics"],
      category: "Game Development",
      projectType: "Personal projects",
      semester: "Personal Project",
      image: "/placeholder.png",
      images: ["/placeholder.png"],
      features: [
        "Low-level programming",
        "Memory management",
        "Console interface",
        "Game logic",
      ],
      github: "https://github.com/XiVolt/Fracture-UP",
    },
    {
      slug: "onlyfoot",
      title: "OnlyFoot - Football Social Network",
      description: "Football community website: photo sharing, user profiles, comments, likes and PostgreSQL database.",
      longDescription: `Social platform dedicated to football allowing users to share their sports moments.`,
      technologies: ["React", "Node.js", "Express", "PostgreSQL", "SQL", "Cloudinary"],
      category: "Web Development",
      projectType: "Personal projects",
      semester: "Personal Project",
      image: "/onlyfoot.png",
      images: ["/onlyfoot.png"],
      features: [
        "User profile creation",
        "Football photo sharing",
        "Comments and likes on posts",
        "PostgreSQL relational database",
        "Secure Node.js API",
        "Image management with Cloudinary",
      ],
    },
    {
      slug: "lensymphony-java",
      title: "LenSymphony - Java Music Synthesizer",
      description: "Development of a functional music synthesizer in Java with XML score reading and real-time sound generation.",
      longDescription: `Complete music synthesizer developed in Java allowing XML format score reading.`,
      technologies: ["Java", "XML", "Music Algorithmics"],
      category: "Software Development",
      projectType: "Student projects",
      semester: "S3 - 2025",
      image: "/Lensymphony2.png",
      images: ["/Lensymphony2.png"],
      features: [
        "Complete music synthesizer",
        "XML score reading",
        "Real-time sound generation",
        "Java user interface",
      ],
      github: "https://gitlab.univ-artois.fr/leo_regniez1/lensymphony-groupe-b-4-regniez-leo-bras-tristan-plouvin-nathan-strobbe-theo",
    },
    {
      slug: "lensymphony-php",
      title: "LenSymphony - PHP Website",
      description: "Development of a PHP website to present and play music created with the LenSymphony synthesizer.",
      longDescription: `Presentation website for the LenSymphony project, allowing to listen to generated music.`,
      technologies: ["PHP", "Sqlite", "CSS3", "JavaScript"],
      category: "Web Development",
      projectType: "Student projects",
      semester: "S3 - 2025",
      image: "/Lensymphony.png",
      images: ["/Lensymphony.png"],
      features: [
        "Music gallery",
        "Integrated audio player",
        "Presentation interface",
        "SQLite database",
      ],
      github: "https://gitlab.univ-artois.fr/nathan_plouvin/leo-tristan-theo-nathan-lensymphony-web",
    },
    {
      slug: "marathon-web-blues",
      title: "Web Marathon - Blues Music Blog",
      description: "Development of a blog site dedicated to blues during a web marathon, with articles, playlists and artist discovery.",
      longDescription: `Thematic blog about blues created during a web marathon, presenting the history and artists of the genre.`,
      technologies: ["PHP", "Sqlite", "CSS3", "JavaScript", "Responsive Design"],
      category: "Web Development",
      projectType: "Student projects",
      semester: "S3 - 2025",
      image: "/Marathon.png",
      images: ["/Marathon.png"],
      features: [
        "Thematic music blog",
        "Blues articles",
        "Playlists and discoveries",
        "Responsive design",
      ],
      github: "https://gitlab.univ-artois.fr/nathan_plouvin/code-marathon-2025-groupe-10",
    },
  ],
  es: [
    {
      slug: "biosymphonie",
      title: "BioSymphonie - Sitio Web Ecorresponsable",
      description: "Creación de un sitio web completo para una empresa de eventos ecorresponsables con navegación multilingüe, carrusel de imágenes y diseño responsive.",
      longDescription: `Este proyecto consistió en crear un sitio web completo para BioSymphonie, una empresa ficticia especializada en la organización de eventos ecorresponsables.`,
      technologies: ["HTML5", "CSS3", "JavaScript", "Responsive Design"],
      category: "Web Development",
      projectType: "Proyectos estudiantiles",
      semester: "S1 - 2024",
      image: "/biosymphonie.png",
      images: ["/biosymphonie.png"],
      features: [
        "Navegación multilingüe (Francés/Inglés)",
        "Diseño responsive adaptativo",
        "Carrusel de imágenes interactivo",
        "Formulario de contacto funcional",
      ],
    },
    {
      slug: "echecs",
      title: "Juego de Ajedrez Interactivo",
      description: "Aplicación web de juego de ajedrez en línea con interfaz gráfica completa, gestión de turnos y sistema de promoción de peones.",
      longDescription: `Desarrollo de una aplicación completa de juego de ajedrez con interfaz web interactiva.`,
      technologies: ["Java", "JavaFX", "Interfaz Web", "Lógica de juego"],
      category: "Game Development",
      projectType: "Proyectos estudiantiles",
      semester: "S1 - 2024",
      image: "/echecs.png",
      images: ["/echecs.png"],
      features: [
        "Interfaz gráfica completa",
        "Gestión de turnos",
        "Sistema de promoción de peones",
        "Validación de movimientos",
      ],
    },
    {
      slug: "bomberman",
      title: "Bomberman - Juego 2D JavaFX",
      description: "Desarrollo de un juego Bomberman completo con arquitectura MVC, animaciones fluidas y gestión de explosiones.",
      longDescription: `Creación de un juego Bomberman en JavaFX con una arquitectura MVC robusta.`,
      technologies: ["JavaFX", "MVC Pattern", "Animación", "Observer Pattern"],
      category: "Game Development",
      projectType: "Proyectos estudiantiles",
      semester: "S2 - 2025",
      image: "/bomberman.png",
      images: ["/bomberman.png"],
      features: [
        "Arquitectura MVC completa",
        "Animaciones Timeline fluidas",
        "Gestión de explosiones",
        "Interfaz responsive",
      ],
      github: "https://github.com/XiVolt/Bomberman",
    },
    {
      slug: "procyon",
      title: "Infraestructura de Red Procyon",
      description: "Configuración completa de una infraestructura de red con servicios DNS/Web, seguridad y alta disponibilidad.",
      longDescription: `Configuración de una infraestructura de red completa incluyendo servicios DNS y Web.`,
      technologies: ["Linux", "DNS (BIND)", "Apache", "IPv4/IPv6", "Seguridad"],
      category: "System Administration",
      projectType: "Proyectos estudiantiles",
      semester: "S2 - 2025",
      image: "/setup.png",
      images: ["/setup.png"],
      features: [
        "Configuración DNS maestro/esclavo",
        "Virtual hosts Apache",
        "Seguridad por zonas",
        "Alta disponibilidad",
      ],
    },
    {
      slug: "algorithmes-tri",
      title: "Análisis de Algoritmos de Ordenamiento",
      description: "Proyecto de análisis comparativo de rendimiento entre diferentes algoritmos de ordenamiento.",
      longDescription: `Análisis profundo de algoritmos de ordenamiento clásicos con comparación de rendimiento.`,
      technologies: ["Java", "Algorítmica", "Análisis de Rendimiento", "Tests Unitarios"],
      category: "Algorithm Analysis",
      projectType: "Proyectos estudiantiles",
      semester: "S1 - 2024",
      image: "/tri.png",
      images: ["/tri.png"],
      features: [
        "Implementación Merge Sort O(n log n)",
        "Quick Sort con pivot optimizado",
        "Mediciones de rendimiento en tiempo real",
        "Análisis comparativo en grandes datos",
      ],
    },
    {
      slug: "base-de-donnees",
      title: "Base de Datos Demográfica",
      description: "Diseño y operación de una base de datos relacional compleja con modelado jerárquico.",
      longDescription: `Diseño de una base de datos relacional para gestión de datos demográficos.`,
      technologies: ["SQL", "PostgreSQL", "Modelado", "Optimización"],
      category: "Database",
      projectType: "Proyectos estudiantiles",
      semester: "S2 - 2025",
      image: "/bd.png",
      images: ["/bd.png"],
      features: [
        "Modelado jerárquico",
        "Joins optimizados",
        "Consultas seguras",
        "Protección de datos",
      ],
    },
    {
      slug: "portfolio-nextjs",
      title: "Portfolio Personal - Next.js",
      description: "Desarrollo de este portfolio con Next.js, animaciones Framer Motion, modo oscuro/claro.",
      longDescription: `Este portfolio fue desarrollado con Next.js y presenta mis proyectos y competencias.`,
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
      category: "Web Development",
      projectType: "Proyectos personales",
      semester: "Proyecto Personal",
      image: "/portfolio.png",
      images: ["/portfolio.png"],
      features: [
        "Modo oscuro/claro",
        "Animaciones fluidas",
        "Rendimiento optimizado",
        "SEO avanzado",
      ],
      github: "https://github.com/XiVolt/Portfolio",
    },
    {
      slug: "volturacode-website",
      title: "VolturaCode - Sitio de Empresa",
      description: "Desarrollo del sitio web de mi empresa VolturaCode, especializada en desarrollo web y ciberseguridad.",
      longDescription: `Sitio web profesional para mi empresa VolturaCode.`,
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "React"],
      category: "Web Development",
      projectType: "Proyectos personales",
      semester: "Proyecto Personal",
      image: "/Voltura.png",
      images: ["/Voltura.png"],
      features: [
        "Diseño moderno",
        "Sitio responsive",
        "Presentación de servicios",
        "Portfolio de clientes",
      ],
      github: "https://github.com/XiVolt/voltura-code-site",
    },
    {
      slug: "jeu-c",
      title: "Juego en C - Desarrollo de bajo nivel",
      description: "Desarrollo de un juego en lenguaje C con gestión de memoria, programación de bajo nivel e interfaz de consola.",
      longDescription: `Desarrollo de un juego en lenguaje C con atención particular a la gestión de memoria y programación de bajo nivel.`,
      technologies: ["C", "Gestión de memoria", "Algorítmica"],
      category: "Game Development",
      projectType: "Proyectos personales",
      semester: "Proyecto Personal",
      image: "/placeholder.png",
      images: ["/placeholder.png"],
      features: [
        "Programación de bajo nivel",
        "Gestión de memoria",
        "Interfaz de consola",
        "Lógica de juego",
      ],
      github: "https://github.com/XiVolt/Fracture-UP",
    },
    {
      slug: "onlyfoot",
      title: "OnlyFoot - Red social de fútbol",
      description: "Sitio web comunitario sobre fútbol: compartir fotos, perfiles de usuario, comentarios, likes y base de datos PostgreSQL.",
      longDescription: `Plataforma social dedicada al fútbol que permite a los usuarios compartir sus momentos deportivos.`,
      technologies: ["React", "Node.js", "Express", "PostgreSQL", "SQL", "Cloudinary"],
      category: "Web Development",
      projectType: "Proyectos personales",
      semester: "Proyecto Personal",
      image: "/onlyfoot.png",
      images: ["/onlyfoot.png"],
      features: [
        "Creación de perfiles de usuario",
        "Compartir fotos de fútbol",
        "Comentarios y likes en publicaciones",
        "Base de datos relacional PostgreSQL",
      ],
    },
    {
      slug: "lensymphony-java",
      title: "LenSymphony - Sintetizador Musical Java",
      description: "Desarrollo de un sintetizador musical funcional en Java con lectura de partituras XML y generación de sonido en tiempo real.",
      longDescription: `Sintetizador musical completo desarrollado en Java que permite la lectura de partituras en formato XML.`,
      technologies: ["Java", "XML", "Algorítmica musical"],
      category: "Software Development",
      projectType: "Proyectos estudiantiles",
      semester: "S3 - 2025",
      image: "/Lensymphony2.png",
      images: ["/Lensymphony2.png"],
      features: [
        "Sintetizador musical completo",
        "Lectura de partituras XML",
        "Generación de sonido en tiempo real",
        "Interfaz de usuario Java",
      ],
      github: "https://gitlab.univ-artois.fr/leo_regniez1/lensymphony-groupe-b-4-regniez-leo-bras-tristan-plouvin-nathan-strobbe-theo",
    },
    {
      slug: "lensymphony-php",
      title: "LenSymphony - Sitio Web PHP",
      description: "Desarrollo de un sitio web en PHP para presentar y reproducir música creada con el sintetizador LenSymphony.",
      longDescription: `Sitio web de presentación para el proyecto LenSymphony.`,
      technologies: ["PHP", "Sqlite", "CSS3", "JavaScript"],
      category: "Web Development",
      projectType: "Proyectos estudiantiles",
      semester: "S3 - 2025",
      image: "/Lensymphony.png",
      images: ["/Lensymphony.png"],
      features: [
        "Galería de músicas",
        "Reproductor de audio integrado",
        "Interfaz de presentación",
        "Base de datos SQLite",
      ],
      github: "https://gitlab.univ-artois.fr/nathan_plouvin/leo-tristan-theo-nathan-lensymphony-web",
    },
    {
      slug: "marathon-web-blues",
      title: "Maratón Web - Blog Musical Blues",
      description: "Desarrollo de un sitio blog dedicado al blues durante un maratón web.",
      longDescription: `Blog temático sobre el blues creado durante un maratón web.`,
      technologies: ["PHP", "Sqlite", "CSS3", "JavaScript", "Responsive Design"],
      category: "Web Development",
      projectType: "Proyectos estudiantiles",
      semester: "S3 - 2025",
      image: "/Marathon.png",
      images: ["/Marathon.png"],
      features: [
        "Blog musical temático",
        "Artículos sobre el blues",
        "Playlists y descubrimientos",
        "Diseño responsive",
      ],
      github: "https://gitlab.univ-artois.fr/nathan_plouvin/code-marathon-2025-groupe-10",
    },
  ],
  de: [
    {
      slug: "biosymphonie",
      title: "BioSymphonie - Umweltfreundliche Website",
      description: "Erstellung einer kompletten Website für ein umweltfreundliches Eventunternehmen mit mehrsprachiger Navigation und responsivem Design.",
      longDescription: `Dieses Projekt bestand darin, eine komplette Website für BioSymphonie zu erstellen, ein fiktives Unternehmen, das sich auf die Organisation umweltfreundlicher Veranstaltungen spezialisiert hat.`,
      technologies: ["HTML5", "CSS3", "JavaScript", "Responsive Design"],
      category: "Web Development",
      projectType: "Studentenprojekte",
      semester: "S1 - 2024",
      image: "/biosymphonie.png",
      images: ["/biosymphonie.png"],
      features: [
        "Mehrsprachige Navigation (Französisch/Englisch)",
        "Adaptives responsives Design",
        "Interaktives Bildkarussell",
        "Funktionales Kontaktformular",
      ],
    },
    {
      slug: "echecs",
      title: "Interaktives Schachspiel",
      description: "Online-Schachspiel-Webanwendung mit vollständiger grafischer Oberfläche und Zugverwaltung.",
      longDescription: `Entwicklung einer kompletten Schachspiel-Anwendung mit interaktiver Web-Oberfläche.`,
      technologies: ["Java", "JavaFX", "Web-Interface", "Spiellogik"],
      category: "Game Development",
      projectType: "Studentenprojekte",
      semester: "S1 - 2024",
      image: "/echecs.png",
      images: ["/echecs.png"],
      features: [
        "Vollständige grafische Oberfläche",
        "Zugverwaltung",
        "Bauernbeförderungssystem",
        "Zugvalidierung",
      ],
    },
    {
      slug: "bomberman",
      title: "Bomberman - 2D JavaFX Spiel",
      description: "Entwicklung eines vollständigen Bomberman-Spiels mit MVC-Architektur und flüssigen Animationen.",
      longDescription: `Erstellung eines Bomberman-Spiels in JavaFX mit robuster MVC-Architektur.`,
      technologies: ["JavaFX", "MVC Pattern", "Animation", "Observer Pattern"],
      category: "Game Development",
      projectType: "Studentenprojekte",
      semester: "S2 - 2025",
      image: "/bomberman.png",
      images: ["/bomberman.png"],
      features: [
        "Vollständige MVC-Architektur",
        "Flüssige Timeline-Animationen",
        "Explosionsverwaltung",
        "Responsive Oberfläche",
      ],
      github: "https://github.com/XiVolt/Bomberman",
    },
    {
      slug: "procyon",
      title: "Procyon Netzwerkinfrastruktur",
      description: "Vollständige Konfiguration einer Netzwerkinfrastruktur mit DNS/Web-Diensten und Sicherheit.",
      longDescription: `Konfiguration einer vollständigen Netzwerkinfrastruktur einschließlich DNS- und Web-Dienste.`,
      technologies: ["Linux", "DNS (BIND)", "Apache", "IPv4/IPv6", "Sicherheit"],
      category: "System Administration",
      projectType: "Studentenprojekte",
      semester: "S2 - 2025",
      image: "/setup.png",
      images: ["/setup.png"],
      features: [
        "Master/Slave-DNS-Konfiguration",
        "Apache Virtual Hosts",
        "Zonenbasierte Sicherheit",
        "Hohe Verfügbarkeit",
      ],
    },
    {
      slug: "algorithmes-tri",
      title: "Sortieralgorithmen-Analyse",
      description: "Vergleichende Leistungsanalyse verschiedener Sortieralgorithmen.",
      longDescription: `Tiefgehende Analyse klassischer Sortieralgorithmen mit Leistungsvergleich.`,
      technologies: ["Java", "Algorithmik", "Leistungsanalyse", "Unit Tests"],
      category: "Algorithm Analysis",
      projectType: "Studentenprojekte",
      semester: "S1 - 2024",
      image: "/tri.png",
      images: ["/tri.png"],
      features: [
        "Merge Sort Implementierung O(n log n)",
        "Quick Sort mit optimiertem Pivot",
        "Echtzeit-Leistungsmessungen",
        "Vergleichsanalyse großer Daten",
      ],
    },
    {
      slug: "base-de-donnees",
      title: "Demografische Datenbank",
      description: "Entwurf und Betrieb einer komplexen relationalen Datenbank mit hierarchischer Modellierung.",
      longDescription: `Entwurf einer relationalen Datenbank für demografische Datenverwaltung.`,
      technologies: ["SQL", "PostgreSQL", "Modellierung", "Optimierung"],
      category: "Database",
      projectType: "Studentenprojekte",
      semester: "S2 - 2025",
      image: "/bd.png",
      images: ["/bd.png"],
      features: [
        "Hierarchische Modellierung",
        "Optimierte Joins",
        "Sichere Abfragen",
        "Datenschutz",
      ],
    },
    {
      slug: "portfolio-nextjs",
      title: "Persönliches Portfolio - Next.js",
      description: "Entwicklung dieses Portfolios mit Next.js, Framer Motion Animationen und Dark/Light Mode.",
      longDescription: `Dieses Portfolio wurde mit Next.js entwickelt und präsentiert meine Projekte interaktiv.`,
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
      category: "Web Development",
      projectType: "Persönliche Projekte",
      semester: "Persönliches Projekt",
      image: "/portfolio.png",
      images: ["/portfolio.png"],
      features: [
        "Dark/Light Mode",
        "Flüssige Animationen",
        "Optimierte Leistung",
        "Erweitertes SEO",
      ],
      github: "https://github.com/XiVolt/Portfolio",
    },
    {
      slug: "volturacode-website",
      title: "VolturaCode - Unternehmenswebsite",
      description: "Entwicklung der Showcase-Website für mein Unternehmen VolturaCode.",
      longDescription: `Professionelle Showcase-Website für mein Unternehmen VolturaCode.`,
      technologies: ["Next.js", "TypeScript", "Tailwind CSS", "React"],
      category: "Web Development",
      projectType: "Persönliche Projekte",
      semester: "Persönliches Projekt",
      image: "/Voltura.png",
      images: ["/Voltura.png"],
      features: [
        "Modernes Design",
        "Responsive Showcase-Site",
        "Dienstleistungspräsentation",
        "Kundenportfolio",
      ],
      github: "https://github.com/XiVolt/voltura-code-site",
    },
    {
      slug: "jeu-c",
      title: "C-Spiel - Low-Level-Entwicklung",
      description: "Entwicklung eines Spiels in C-Sprache mit Speicherverwaltung, Low-Level-Programmierung und Konsolenschnittstelle.",
      longDescription: `Entwicklung eines Spiels in C-Sprache mit besonderer Aufmerksamkeit auf Speicherverwaltung und Low-Level-Programmierung.`,
      technologies: ["C", "Speicherverwaltung", "Algorithmik"],
      category: "Game Development",
      projectType: "Persönliche Projekte",
      semester: "Persönliches Projekt",
      image: "/placeholder.png",
      images: ["/placeholder.png"],
      features: [
        "Low-Level-Programmierung",
        "Speicherverwaltung",
        "Konsolenschnittstelle",
        "Spiellogik",
      ],
      github: "https://github.com/XiVolt/Fracture-UP",
    },
    {
      slug: "onlyfoot",
      title: "OnlyFoot - Fußball-Soziales Netzwerk",
      description: "Community-Website zum Fußball: Fotos teilen, Benutzerprofile, Kommentare, Likes und PostgreSQL-Datenbank.",
      longDescription: `Soziale Plattform für Fußball, die Benutzern ermöglicht, ihre sportlichen Momente zu teilen.`,
      technologies: ["React", "Node.js", "Express", "PostgreSQL", "SQL", "Cloudinary"],
      category: "Web Development",
      projectType: "Persönliche Projekte",
      semester: "Persönliches Projekt",
      image: "/onlyfoot.png",
      images: ["/onlyfoot.png"],
      features: [
        "Benutzerprofilerstellung",
        "Fußballfotos teilen",
        "Kommentare und Likes auf Beiträge",
        "PostgreSQL relationale Datenbank",
      ],
    },
    {
      slug: "lensymphony-java",
      title: "LenSymphony - Java-Musik-Synthesizer",
      description: "Entwicklung eines funktionalen Musik-Synthesizers in Java mit XML-Partiturlesung und Echtzeit-Klangerzeugung.",
      longDescription: `Kompletter Musik-Synthesizer in Java entwickelt, der das Lesen von Partituren im XML-Format ermöglicht.`,
      technologies: ["Java", "XML", "Musikalgorithmik"],
      category: "Software Development",
      projectType: "Studentenprojekte",
      semester: "S3 - 2025",
      image: "/Lensymphony2.png",
      images: ["/Lensymphony2.png"],
      features: [
        "Kompletter Musik-Synthesizer",
        "XML-Partiturlesung",
        "Echtzeit-Klangerzeugung",
        "Java-Benutzeroberfläche",
      ],
      github: "https://gitlab.univ-artois.fr/leo_regniez1/lensymphony-groupe-b-4-regniez-leo-bras-tristan-plouvin-nathan-strobbe-theo",
    },
    {
      slug: "lensymphony-php",
      title: "LenSymphony - PHP-Website",
      description: "Entwicklung einer PHP-Website zur Präsentation und Wiedergabe von Musik, die mit dem LenSymphony-Synthesizer erstellt wurde.",
      longDescription: `Präsentationswebsite für das LenSymphony-Projekt.`,
      technologies: ["PHP", "Sqlite", "CSS3", "JavaScript"],
      category: "Web Development",
      projectType: "Studentenprojekte",
      semester: "S3 - 2025",
      image: "/Lensymphony.png",
      images: ["/Lensymphony.png"],
      features: [
        "Musikgalerie",
        "Integrierter Audioplayer",
        "Präsentationsoberfläche",
        "SQLite-Datenbank",
      ],
      github: "https://gitlab.univ-artois.fr/nathan_plouvin/leo-tristan-theo-nathan-lensymphony-web",
    },
    {
      slug: "marathon-web-blues",
      title: "Web-Marathon - Blues-Musik-Blog",
      description: "Entwicklung einer Blog-Website zum Thema Blues während eines Web-Marathons.",
      longDescription: `Thematischer Blog über Blues, erstellt während eines Web-Marathons.`,
      technologies: ["PHP", "Sqlite", "CSS3", "JavaScript", "Responsive Design"],
      category: "Web Development",
      projectType: "Studentenprojekte",
      semester: "S3 - 2025",
      image: "/Marathon.png",
      images: ["/Marathon.png"],
      features: [
        "Thematischer Musik-Blog",
        "Artikel über Blues",
        "Playlists und Entdeckungen",
        "Responsives Design",
      ],
      github: "https://gitlab.univ-artois.fr/nathan_plouvin/code-marathon-2025-groupe-10",
    },
  ],
};

